# Generated by Django 5.0.6 on 2024-10-19 10:35

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('summary', models.CharField()),
                ('image', models.CharField()),
                ('author', models.CharField()),
                ('published_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('title_embed', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('summary_embed', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksTags',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_id', models.IntegerField()),
            ],
            options={
                'db_table': 'books_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
    ]
